= admincontainer

General purpose container mainly for admin purposes. The idea of this container is to provide a set of tools that can be used using Linux, Windows or Mac workstation without installing the tools natively. 

The container is especially useful when using Windows workstation to administer Linux servers and when using multiple workstations.

Notes:

* Rocky Linux is chosen as base because most enterprise Linux servers use Red Hat based servers.
* no systemd.
* no graphical interface.

The container is not meant as replacement of a workstation but to provide a helper tool that could be used when feasible.

== Usage

* Create directory where you want to put your own scripts, data, etc.
** For example: `C:\HOME\work\development\admincontainer`
* Use image:
** `docker run -it --rm -v C:\HOME\work\development\admincontainer\:/root/host --name admincontainer -h admincontainer -p 2022:22 kazhar/admincontainer`
** Options:
*** Use _/root/host_ as directory inside container (-v </your/dir/>:/root/host), configuration uses that directory.
*** Use hostname _admincontainer_ (-h admincontainer), SSH key uses that host.
*** Set ports using -p option.

.Environment variables when starting the container
|===
|Name|Value|Description

|DISABLE_SSHD
|<any text>
|Do not start ssh daemon.

|ROOT_PASSWORD
|<any pwd>
|Set root password.

|WRITE_ROOT_PASSWORD_TO_FILE
|<any text>
|Write root password to /root/root_pwd.txt.

|DISPLAY
|<X display>
|Set display for X (default is `host.docker.internal:0` for Windows hosts).

(X server running on host is required.)

|START_WETTY_HTTP
|<any text>
|Start HTTP WeTTY server instead of bash-shell.

|START_WETTY_HTTPS
|<any text>
|Start HTTPS WeTTY server instead of bash-shell.

|===


.Ports inside the container
|===
|Port|Description

|22
|SSH port, expose using for example `-p 2022:22`

|3000
|WeTTY port, expose using for example `-p 3000:3000`

|===


=== Build

Build your own version of admincontainer.

* Modify Dockerfile, if required, to install new packages etc.
* Set your own environment variables in _Dockerfile_, _environment.sh_ and _shell.sh_.
* Build image:
** `docker build -t myadmin .`
* Use image:
** `docker run -it --rm -v C:\HOME\work\development\admincontainer:/root/host --name admincontainer -h admincontainer -p 2022:22 myadmin`

== Tools

Container provides some tools and more can be added easily by modifying Dockerfile.

* OpenShift/Kubernetes clients, oc and kubectl
* https://github.com/samisalkosuo/kubeterminal[KubeTerminal]
* Node.js
* lynx and w3m - text based browsers
* https://github.com/butlerx/wetty[WeTTY]
* SSH daemon, so SSH client can be used to access the container.
** root-user is used to access the container, root password is generated when container is started.
* Tmux with https://github.com/gpakosz/.tmux and tmux-restore - remembers tmux windows between restarts.
** Inside container get Tmux cheatsheet: `w3m https://tmuxcheatsheet.com/`
* xclip - if you have X server, you can copy from container to host clipboard.
